import type { NodeWidgetLayout } from '../types';

export const SDXLEmptyLatentImagergthree: NodeWidgetLayout = {
    nodeType: 'SDXL Empty Latent Image (rgthree)',
    displayName: 'SDXL Empty Latent Image (rgthree)',
    category: 'rgthree',
    github: {
        repo: 'https://github.com/rgthree/rgthree-comfy',
        path: 'py/sdxl_empty_latent_image.py',
        extension: 'rgthree-comfy',
    },
    widgets: [
        {
            name: 'dimensions',
            label: 'Dimensions',
            widgetType: 'COMBO',
            options: [
                '512 x 512',
                '768 x 768',
                '1024 x 1024',
                '1024 x 576',
                '576 x 1024',
                '1152 x 896',
                '896 x 1152',
                '1216 x 832',
                '832 x 1216',
                '1344 x 768',
                '768 x 1344',
                '1536 x 640',
                '640 x 1536',
            ],
            default: '1024 x 1024',
        },
        {
            name: 'clip_scale',
            label: 'CLIP Scale',
            widgetType: 'FLOAT',
            default: 2.0,
            min: 1.0,
            max: 12.0,
            step: 0.1,
            display: 'number',
        },
        {
            name: 'batch_size',
            label: 'Batch Size',
            widgetType: 'INT',
            default: 1,
            min: 1,
            max: 4096,
            step: 1,
            display: 'number',
        },
    ],
};
