import type { NodeWidgetLayout } from './types';

export const CLIPTextEncodeSDXL: NodeWidgetLayout = {
    nodeType: 'CLIPTextEncodeSDXL',
    displayName: 'CLIP Text Encode SDXL',
    category: 'conditioning',
    widgets: [
        {
            name: 'text_g',
            label: 'Text (G)',
            widgetType: 'STRING',
            multiline: true,
            default: '',
            dynamicPrompts: true,
        },
        {
            name: 'text_l',
            label: 'Text (L)',
            widgetType: 'STRING',
            multiline: true,
            default: '',
            dynamicPrompts: true,
        },
        {
            name: 'crop_w',
            label: 'Crop Width',
            widgetType: 'INT',
            default: 0,
            min: 0,
            max: 12800,
        },
        {
            name: 'crop_h',
            label: 'Crop Height',
            widgetType: 'INT',
            default: 0,
            min: 0,
            max: 12800,
        },
        {
            name: 'target_w',
            label: 'Target Width',
            widgetType: 'INT',
            default: 0,
            min: 0,
            max: 12800,
        },
        {
            name: 'target_h',
            label: 'Target Height',
            widgetType: 'INT',
            default: 0,
            min: 0,
            max: 12800,
        },
        {
            name: 'width',
            label: 'Width',
            widgetType: 'INT',
            default: 1024,
            min: 0,
            max: 12800,
        },
        {
            name: 'height',
            label: 'Height',
            widgetType: 'INT',
            default: 1024,
            min: 0,
            max: 12800,
        },
        {
            name: 'target_width',
            label: 'Target Width (Generation)',
            widgetType: 'INT',
            default: 1024,
            min: 0,
            max: 12800,
        },
        {
            name: 'target_height',
            label: 'Target Height (Generation)',
            widgetType: 'INT',
            default: 1024,
            min: 0,
            max: 12800,
        },
    ],
};
