import type { NodeWidgetLayout } from './types';
import { SAMPLER_NAMES, SCHEDULER_NAMES } from './types';

export const ClownsharKSampler_Beta: NodeWidgetLayout = {
    nodeType: 'ClownsharKSampler_Beta',
    displayName: 'ClownsharKSampler (Beta)',
    category: 'RES4LYF/samplers',
    github: {
        repo: 'https://github.com/ClownsharkBatwing/RES4LYF',
        path: 'beta/samplers.py',
        extension: 'RES4LYF',
    },
    widgets: [
        {
            name: 'eta',
            label: 'Eta',
            widgetType: 'FLOAT',
            default: 0.5,
            min: -100.0,
            max: 100.0,
            step: 0.01,
            round: false,
            display: 'slider',
            tooltip: 'Calculated noise amount to be added, then removed, after each step.',
        },
        {
            name: 'sampler_name',
            label: 'Sampler',
            widgetType: 'COMBO',
            options: [...SAMPLER_NAMES],
            default: 'euler',
            tooltip: 'Sampling algorithm used for denoising.',
        },
        {
            name: 'scheduler',
            label: 'Scheduler',
            widgetType: 'COMBO',
            options: [...SCHEDULER_NAMES],
            default: 'beta',
            tooltip: 'Noise schedule for the denoising process.',
        },
        {
            name: 'steps',
            label: 'Steps',
            widgetType: 'INT',
            default: 30,
            min: 1,
            max: 10000,
            step: 1,
            display: 'number',
            tooltip: 'Number of denoising steps.',
        },
        {
            name: 'steps_to_run',
            label: 'Steps to Run',
            widgetType: 'INT',
            default: -1,
            min: -1,
            max: 10000,
            step: 1,
            display: 'number',
            tooltip: 'Number of steps to actually run. -1 uses the steps value.',
        },
        {
            name: 'denoise',
            label: 'Denoise',
            widgetType: 'FLOAT',
            default: 1.0,
            min: 0.0,
            max: 1.0,
            step: 0.01,
            display: 'slider',
            tooltip: 'Denoising strength. 1.0 = full generation, <1.0 = img2img.',
        },
        {
            name: 'cfg',
            label: 'CFG',
            widgetType: 'FLOAT',
            default: 5.5,
            min: -100.0,
            max: 100.0,
            step: 0.01,
            round: false,
            display: 'slider',
            tooltip: 'Classifier-Free Guidance scale. Negative values use channelwise CFG.',
        },
        {
            name: 'seed',
            label: 'Seed',
            widgetType: 'INT',
            default: 0,
            min: -1,
            max: 0xffffffffffffffff,
            display: 'number',
            linkedTo: 'control_after_generate',
            tooltip: 'Random seed for noise generation. Same seed = same image.',
        },
        {
            name: 'control_after_generate',
            label: 'Control After Generate',
            widgetType: 'COMBO',
            options: ['randomize', 'increment', 'decrement', 'keep'],
            default: 'randomize',
            tooltip: 'What to do with the seed after each generation.',
        },
        {
            name: 'sampler_mode',
            label: 'Sampler Mode',
            widgetType: 'COMBO',
            options: ['unsample', 'standard', 'resample'],
            default: 'standard',
            tooltip: 'Sampling mode: standard, unsample (reverse), or resample.',
        },
        {
            name: 'bongmath',
            label: 'Bong Math',
            widgetType: 'BOOLEAN',
            default: true,
            tooltip: 'Activates advanced noise calculations using bongmath.',
        },
    ],
};
