import type { NodeWidgetLayout } from './types';

export const EmptyLTXVLatentVideo: NodeWidgetLayout = {
    nodeType: 'EmptyLTXVLatentVideo',
    displayName: 'Empty LTXV Latent Video',
    category: 'model/latent/ltxv',
    github: {
        repo: 'https://github.com/comfyanonymous/ComfyUI',
        path: 'comfy_extras/nodes_lt.py',
        extension: 'ComfyUI',
    },
    widgets: [
        {
            name: 'width',
            label: 'Width',
            widgetType: 'INT',
            default: 768,
            min: 64,
            max: 16384,
            step: 32,
            display: 'number',
            tooltip: 'The width of the latent video in pixels.',
        },
        {
            name: 'height',
            label: 'Height',
            widgetType: 'INT',
            default: 512,
            min: 64,
            max: 16384,
            step: 32,
            display: 'number',
            tooltip: 'The height of the latent video in pixels.',
        },
        {
            name: 'length',
            label: 'Length',
            widgetType: 'INT',
            default: 97,
            min: 1,
            max: 16384,
            step: 8,
            display: 'number',
            tooltip: 'The number of frames in the latent video.',
        },
        {
            name: 'batch_size',
            label: 'Batch Size',
            widgetType: 'INT',
            default: 1,
            min: 1,
            max: 4096,
            step: 1,
            display: 'number',
            tooltip: 'Number of latent videos to generate.',
        },
    ],
};
