import type { NodeWidgetLayout } from './types';
import { SAMPLER_NAMES, SCHEDULER_NAMES } from './types';

export const KSamplerAdvanced: NodeWidgetLayout = {
    nodeType: 'KSamplerAdvanced',
    displayName: 'KSampler (Advanced)',
    category: 'sampling',
    widgets: [
        {
            name: 'noise_seed',
            label: 'Noise Seed',
            widgetType: 'INT',
            default: 0,
            min: 0,
            max: 0xffffffffffffffff,
            display: 'number',
            linkedTo: 'control_after_generate',
        },
        {
            name: 'control_after_generate',
            label: 'Control After Generate',
            widgetType: 'COMBO',
            options: ['randomize', 'increment', 'decrement', 'keep'],
            default: 'randomize',
        },
        {
            name: 'steps',
            label: 'Steps',
            widgetType: 'INT',
            default: 20,
            min: 1,
            max: 10000,
            step: 1,
            display: 'number',
        },
        {
            name: 'cfg',
            label: 'CFG',
            widgetType: 'FLOAT',
            default: 8.0,
            min: 0.0,
            max: 100.0,
            step: 0.1,
            round: 0.01,
            display: 'slider',
        },
        {
            name: 'sampler_name',
            label: 'Sampler',
            widgetType: 'COMBO',
            options: [...SAMPLER_NAMES],
            default: 'euler',
        },
        {
            name: 'scheduler',
            label: 'Scheduler',
            widgetType: 'COMBO',
            options: [...SCHEDULER_NAMES],
            default: 'normal',
        },
        {
            name: 'denoise',
            label: 'Denoise',
            widgetType: 'FLOAT',
            default: 1.0,
            min: 0.0,
            max: 1.0,
            step: 0.01,
            display: 'slider',
        },
        {
            name: 'start_at_step',
            label: 'Start Step',
            widgetType: 'FLOAT',
            default: 0.0,
            min: 0.0,
            max: 1.0,
            step: 0.01,
            display: 'number',
        },
        {
            name: 'end_at_step',
            label: 'End Step',
            widgetType: 'FLOAT',
            default: 1.0,
            min: 0.0,
            max: 1.0,
            step: 0.01,
            display: 'number',
        },
        {
            name: 'return_with_leftover_noise',
            label: 'Return with Leftover Noise',
            widgetType: 'COMBO',
            options: ['disable', 'enable'],
            default: 'disable',
        },
    ],
};
