import type { NodeWidgetLayout } from './types';
import { SAMPLER_NAMES, SCHEDULER_NAMES } from './types';

export const KSampler: NodeWidgetLayout = {
    nodeType: 'KSampler',
    displayName: 'KSampler',
    category: 'sampling',
    widgets: [
        {
            name: 'seed',
            label: 'Seed',
            widgetType: 'INT',
            default: 0,
            min: 0,
            max: 0xffffffffffffffff,
            display: 'number',
            linkedTo: 'control_after_generate',
            tooltip: 'Random seed for noise generation. Same seed = same image.',
        },
        {
            name: 'control_after_generate',
            label: 'Control After Generate',
            widgetType: 'COMBO',
            options: ['randomize', 'increment', 'decrement', 'keep'],
            default: 'randomize',
            tooltip: 'What to do with the seed after each generation.',
        },
        {
            name: 'steps',
            label: 'Steps',
            widgetType: 'INT',
            default: 20,
            min: 1,
            max: 10000,
            step: 1,
            display: 'number',
            tooltip: 'Number of denoising steps. More steps = more refined output.',
        },
        {
            name: 'cfg',
            label: 'CFG',
            widgetType: 'FLOAT',
            default: 8.0,
            min: 0.0,
            max: 100.0,
            step: 0.1,
            round: 0.01,
            display: 'slider',
            tooltip: 'Classifier-Free Guidance scale. Higher = closer to prompt.',
        },
        {
            name: 'sampler_name',
            label: 'Sampler',
            widgetType: 'COMBO',
            options: [...SAMPLER_NAMES],
            default: 'euler',
            tooltip: 'Sampling algorithm used for denoising.',
        },
        {
            name: 'scheduler',
            label: 'Scheduler',
            widgetType: 'COMBO',
            options: [...SCHEDULER_NAMES],
            default: 'normal',
            tooltip: 'Noise schedule for the denoising process.',
        },
        {
            name: 'denoise',
            label: 'Denoise',
            widgetType: 'FLOAT',
            default: 1.0,
            min: 0.0,
            max: 1.0,
            step: 0.01,
            display: 'slider',
            tooltip: 'Denoising strength. 1.0 = full generation, <1.0 = img2img.',
        },
    ],
};
