import type { NodeWidgetLayout } from './types';

export const LoraLoaderStackrgthree: NodeWidgetLayout = {
    nodeType: 'Lora Loader Stack (rgthree)',
    displayName: 'Lora Loader Stack (rgthree)',
    category: 'rgthree',
    github: {
        repo: 'https://github.com/rgthree/rgthree-comfy',
        path: 'py/lora_loader_stack.py',
        extension: 'rgthree-comfy',
    },
    widgets: [
        {
            name: 'lora_01',
            label: 'LoRA 1',
            widgetType: 'COMBO',
            options: [],
        },
        {
            name: 'strength_01',
            label: 'Strength 1',
            widgetType: 'FLOAT',
            default: 1.0,
            min: -20.0,
            max: 20.0,
            step: 0.01,
            display: 'number',
        },
        {
            name: 'lora_02',
            label: 'LoRA 2',
            widgetType: 'COMBO',
            options: [],
        },
        {
            name: 'strength_02',
            label: 'Strength 2',
            widgetType: 'FLOAT',
            default: 1.0,
            min: -20.0,
            max: 20.0,
            step: 0.01,
            display: 'number',
        },
        {
            name: 'lora_03',
            label: 'LoRA 3',
            widgetType: 'COMBO',
            options: [],
        },
        {
            name: 'strength_03',
            label: 'Strength 3',
            widgetType: 'FLOAT',
            default: 1.0,
            min: -20.0,
            max: 20.0,
            step: 0.01,
            display: 'number',
        },
        {
            name: 'lora_04',
            label: 'LoRA 4',
            widgetType: 'COMBO',
            options: [],
        },
        {
            name: 'strength_04',
            label: 'Strength 4',
            widgetType: 'FLOAT',
            default: 1.0,
            min: -20.0,
            max: 20.0,
            step: 0.01,
            display: 'number',
        },
    ],
};
