import type { NodeWidgetLayout } from './types';

export const VAEEncodeTiled: NodeWidgetLayout = {
    nodeType: 'VAEEncodeTiled',
    displayName: 'VAE Encode (Tiled)',
    category: 'model/latent',
    github: {
        repo: 'https://github.com/comfyanonymous/ComfyUI',
        path: 'nodes.py',
        extension: 'ComfyUI',
    },
    widgets: [
        {
            name: 'tile_size',
            label: 'Tile Size',
            widgetType: 'INT',
            default: 512,
            min: 64,
            max: 4096,
            step: 64,
            advanced: true,
        },
        {
            name: 'overlap',
            label: 'Overlap',
            widgetType: 'INT',
            default: 64,
            min: 0,
            max: 4096,
            step: 32,
            advanced: true,
        },
        {
            name: 'temporal_size',
            label: 'Temporal Size',
            widgetType: 'INT',
            default: 64,
            min: 8,
            max: 4096,
            step: 4,
            advanced: true,
            tooltip: 'Only used for video VAEs: Amount of frames to encode at a time.',
        },
        {
            name: 'temporal_overlap',
            label: 'Temporal Overlap',
            widgetType: 'INT',
            default: 8,
            min: 4,
            max: 4096,
            step: 4,
            advanced: true,
            tooltip: 'Only used for video VAEs: Amount of frames to overlap.',
        },
    ],
};
